name: Build Juridical Console

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (OpenJDK 21)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Leiningen dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install Leiningen
        run: |
          curl -L https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o lein
          chmod +x lein
          sudo mv lein /usr/local/bin/

      - name: Build project (uberjar)
        run: |
          lein clean
          lein uberjar

      - name: List generated artifacts
        run: ls -lah target
